### ISSUE TITLE
Prework for issue #208

### ISSUE THREAD

**Issue by jacob-chia** [fuzzland/ityfuzz#235]
## TODO

- [x] fix build errors when enabling `sui_support`
- [x] fix test errors when enabling `sui_support`
- [x] merge `core` into `src` and remove `core`

**Comment by 0xAWM** [comment]
Thx for your plan.

I think we can safely remove the `core` dir. Will be done after CI #236 .

for `sui_support` feature, the error may be caused by the removal of submodule:
https://github.com/fuzzland/ityfuzz/blob/80e5c7c5223ec09b913f5e94c2cd0e63780786ed/Cargo.toml#L29-L37
https://github.com/fuzzland/ityfuzz/blob/80e5c7c5223ec09b913f5e94c2cd0e63780786ed/Cargo.toml#L91-L105

I guess replacing it with `cargo git` will solve the problem. Hope you can help test it

**Comment by jacob-chia** [comment]
@0xAWM OK, I'll fix the sui errors.
